import { Data, TaskTypes } from './types/types'

export const initialData: Data = {
  tasks: {
    'task-1': {
      id: 'task-1',
      slug: 'TSK-01',
      title: 'Find a dnd library',
      priority: 1,
      type: TaskTypes.EPIC,
      storyPoints: 3,
    },
    'task-2': {
      id: 'task-2',
      slug: 'TSK-02',
      title: 'Init project',
      priority: 1,
      type: TaskTypes.EPIC,
      storyPoints: 5,
    },
    'task-3': {
      id: 'task-3',
      slug: 'TSK-03',
      title: 'Implement drag and drop',
      priority: 1,
      type: TaskTypes.EPIC,
    },
    'task-4': {
      id: 'task-4',
      slug: 'TSK-04',
      title: 'Implement business logic',
      priority: 1,
      type: TaskTypes.EPIC,
      storyPoints: 13,
    },
    'task-5': {
      id: 'task-5',
      slug: 'TSK-05',
      title: 'Refactor code for readability',
      priority: 2,
      type: TaskTypes.EPIC,
    },
    'task-6': {
      id: 'task-6',
      slug: 'TSK-06',
      title: 'Write unit tests for new feature',
      priority: 1,
      type: TaskTypes.EPIC,
      storyPoints: 2,
    },
    'task-7': {
      id: 'task-7',
      slug: 'TSK-07',
      title: 'Review and merge pull request',
      priority: 3,
      type: TaskTypes.TASK,
    },
    'task-8': {
      id: 'task-8',
      slug: 'TSK-08',
      title: 'Deploy code to production',
      priority: 1,
      type: TaskTypes.TASK,
    },
    'task-9': {
      id: 'task-9',
      slug: 'TSK-09',
      title: 'Create documentation for API endpoints',
      priority: 2,
      type: TaskTypes.TASK,
      storyPoints: 1,
    },
    'task-10': {
      id: 'task-10',
      slug: 'TSK-10',
      title: 'Refactor database schema',
      priority: 3,
      type: TaskTypes.EPIC,
    },
    'task-11': {
      id: 'task-11',
      slug: 'TSK-11',
      title: 'Implement user authentication',
      priority: 1,
      type: TaskTypes.EPIC,
    },
    'task-12': {
      id: 'task-12',
      slug: 'TSK-12',
      title: 'Optimize database queries',
      priority: 2,
      type: TaskTypes.EPIC,
      storyPoints: 0.5,
    },
    'task-13': {
      id: 'task-13',
      slug: 'TSK-13',
      title: 'Add error handling to API endpoints',
      priority: 1,
      type: TaskTypes.TASK,
    },
    'task-14': {
      id: 'task-14',
      slug: 'TSK-14',
      title: 'Write integration tests for new feature',
      priority: 2,
      type: TaskTypes.TASK,
    },
    'task-15': {
      id: 'task-15',
      slug: 'TSK-15',
      title: 'Create user interface design mockups',
      priority: 3,
      type: TaskTypes.TASK,
    },
    'task-16': {
      id: 'task-16',
      slug: 'TSK-16',
      title: 'Implement pagination for API endpoints',
      priority: 2,
      type: TaskTypes.TASK,
    },
    'task-17': {
      id: 'task-17',
      slug: 'TSK-17',
      title: 'Add support for multiple languages',
      priority: 3,
      type: TaskTypes.TASK,
    },
    'task-18': {
      id: 'task-18',
      slug: 'TSK-18',
      title: 'Create automated deployment script',
      priority: 1,
      type: TaskTypes.TASK,
    },
    'task-19': {
      id: 'task-19',
      slug: 'TSK-19',
      title: 'Implement caching for frequently accessed data',
      priority: 2,
      type: TaskTypes.TASK,
    },
    'task-20': {
      id: 'task-20',
      slug: 'TSK-20',
      title: 'Add support for file uploads',
      priority: 1,
      type: TaskTypes.EPIC,
    },
  },
  columns: {
    backlog: {
      id: 'backlog',
      title: 'Backlog',
      taskIds: [],
      icon: 'backlog',
    },
    todo: {
      id: 'todo',
      title: 'To do',
      taskIds: [
        'task-1',
        'task-2',
        'task-3',
        'task-4',
        'task-5',
        'task-6',
        'task-7',
        'task-8',
        'task-9',
        'task-10',
        'task-11',
        'task-12',
        'task-13',
        'task-14',
        'task-15',
        'task-16',
        'task-17',
        'task-18',
        'task-19',
        'task-20',
      ],
      icon: 'todo',
    },
    in_progress: {
      id: 'in_progress',
      title: 'In Progress',
      taskIds: [],
      icon: 'in_progress',
    },
    test: {
      id: 'test',
      title: 'Test',
      taskIds: [],
      icon: 'test',
    },
  },
  latestTaskId: 20,
}
